name = "Steam Modpack"
author = "Alex"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "678a9720594ee11c21f166ca8a3220db1e64dac061ad89339dfc928e6dbe42fc"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
