name = "Steam Modpack"
author = "Alex"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eebdff90788c3562eaebad103fd79a826ddba725aa966d0b057070195d686a1d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
