name = "Steam Modpack"
author = "Alex"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84c978e58449bfbe6dc30f8b7d084c7debdd85da054f25476fca6b22195e2d20"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
