name = "Steam Modpack"
author = "Alex"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "412a80d074ab021646d4f98302ae66a2d95e89e9d663dcec8649351166c56018"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
