name = "Steam Modpack"
author = "Alex"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "811c40cca924f3816e8084cf6bf0f291ff9593586d033da34107b4667dd8db62"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
